spring:
    datasource:
      driverClassName: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@192.168.11.120:1521:orcl
      username: dev
      password: dev
    thymeleaf.cache: false
security.basic.enabled: false

sks:
  mail:
    host: smtp.gmail.com
    port: 587
    username: <Your Account>@gmail.com
    password: <Your Password>